### ISSUE TITLE
noble folder is empty

### ISSUE THREAD

**Issue by ClonzEh** [NobleRobot/NobleEngine-ProjectTemplate#8]
followed instructions, cloned this template, noble folder empty.

**Comment by Mark-LaCroix** [comment]
You _can_ do that, but the main Noble Engine project is already configured as a "git submodule" of this project, which makes it easier to pull changes to the engine without having to re-download or clone it every time there are updates. That way, your project is never handcuffed to a specific version of Noble Engine.

Submodules are not the most intuitive topic if you're not already familiar with it, but if you're using a git client with a GUI, like Fork or SourceTree, they're trivially pretty easy to use.

If you're using git on the command line, and you've already cloned the template project, you can use this command to pull the Engine:
`git submodule update --init --recursive`

If you're cloning this project (or a new project which you created using this as a GitHub Template) for the first time, you can do it all in one go with this command, which clones the project with the "recurse submodules" flag:
`git clone --recursive https://github.com/NobleRobot/NobleEngine-ProjectTemplate.git`

Here's a GitHub article on the topic: https://github.blog/2016-02-01-working-with-submodules/
